# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "DEV"
  DEV:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Run a script
      run: |
        echo "Hello ${{ inputs.name }}"

  # This workflow contains a single job called "Preview"
  Preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Preview
    needs: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Run a script
      run: |
        echo "Hello ${{ inputs.name }}"

# This workflow contains a single job called "Production"
  Production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    needs: Preview

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Run a script
      run: |
        echo "Hello ${{ inputs.name }}"
